# This is a basic workflow to help you get started with Actions
# Trying demo for the branch protection on the main.
# Demo for Code Approver(by poc-coe) to main (not even admins allowed).

name: CI

# Controls when the workflow will runss
on:
  # Triggers the workflow on push to "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallelxxx
jobs:
  compute-environment:
  runs-on: ubuntu-latest
    steps:
      - name: "Compute Environment"
        run: |
          if contains(github.ref, 'feature/')
          then
            echo "Branch is feature"
            echo "C_ENV=bus" >> $GITHUB_ENV
          else
            echo "Branch is NOT from feature"
            echo "C_ENV=dev-tst" >> $GITHUB_ENV
          fi
          echo "C_ENV is $C_ENV"
        shell: bash
  # This workflow contains a single job called "build"
  dev-tst:
    if: github.ref_name == 'main'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev-tst

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  # This workflow contains a single job called "build"
  bus:
    # this condition will need change. ref_name will just last name of the branch, not whole brnach name
    if: contains(github.ref, 'feature/')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: bus

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
